name: spaceships
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  gradient_borders: ^1.0.0
  pinput: ^4.0.0
  blurrycontainer: ^1.0.2
  flashy_tab_bar2: ^0.0.10
  flutter_staggered_grid_view: ^0.4.0
  flutter_slidable: ^3.1.0
  animate_gradient: ^0.0.2
  change_app_package_name: ^1.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0

  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  email_otp: ^2.1.2
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0




  firebase_database: ^11.0.2
 

  firebase_messaging: ^15.0.3
  fluttertoast: ^8.2.6
  dropdown_button2: ^2.3.9
  loading_animation_widget: ^1.2.1
  permission_handler: ^11.3.1
  firebase_app_check: ^0.3.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos.png
    - assets/images/OnBoardingSplash.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logos.png"
