// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGSDoWw_9nqnaD3b78j-Nwx0VCxz3dQY',
    appId: '1:920411121805:web:774a4190e7b0a5f4449ac4',
    messagingSenderId: '920411121805',
    projectId: 'spaceships-51250',
    authDomain: 'spaceships-51250.firebaseapp.com',
    databaseURL: 'https://spaceships-51250-default-rtdb.firebaseio.com',
    storageBucket: 'spaceships-51250.appspot.com',
    measurementId: 'G-XPBRJFMKC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumrB8byZbpHeS9si50-Q1N3wzoYa-4NY',
    appId: '1:920411121805:android:9e1a0b6cb38422f9449ac4',
    messagingSenderId: '920411121805',
    projectId: 'spaceships-51250',
    databaseURL: 'https://spaceships-51250-default-rtdb.firebaseio.com',
    storageBucket: 'spaceships-51250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW2UGlUfCw4N79Qq_n2R5A6jIKG0N6dpA',
    appId: '1:920411121805:ios:cfc83b689789710b449ac4',
    messagingSenderId: '920411121805',
    projectId: 'spaceships-51250',
    databaseURL: 'https://spaceships-51250-default-rtdb.firebaseio.com',
    storageBucket: 'spaceships-51250.appspot.com',
    iosClientId: '920411121805-spmj4m0as50co1fll0o0piouov38jdss.apps.googleusercontent.com',
    iosBundleId: 'com.app.spaceships',
  );
}
